manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: urob
      revision: 52e4e91
      import: app/west.yml
  self:
    path: config
